// Short "famous for" notes used as the first hint in the Karnataka district
// map puzzle. Keys match the district names in india.geojson exactly.

export const KA_DISTRICT_FACTS: Record<string, string> = {
  Bagalkote: "Badami & Aihole rock-cut temples; Pattadakal (UNESCO)",
  Ballari: "Hampi ruins (Vijayanagara empire, UNESCO); iron-ore mining",
  Belagavi: "Kunda sweet; sugar belt; the second 'Suvarna' assembly",
  "Bengaluru Rural": "Nandi Hills; Devanahalli airport; grapes",
  "Bengaluru Urban": "India's IT capital ('Silicon Valley'); Vidhana Soudha",
  Bidar: "Bidriware metal craft; Bahmani fort & tombs",
  Chamarajanagara: "BR Hills & sandalwood; Male Mahadeshwara temple",
  Chikkaballapura: "Nandi Hills & silk; home of Sir M. Visvesvaraya",
  Chikkamagaluru: "Birthplace of Indian coffee; Mullayanagiri (highest peak)",
  Chitradurga: "Massive stone fortress (Kallina Kote); wind farms",
  "Dakshina Kannada": "Mangaluru port; Kambala buffalo race; banking cradle",
  Davanagere: "Benne (butter) dosa; cotton, 'Manchester of Karnataka'",
  Dharwad: "Dharwad pedha (GI); Hindustani music; universities",
  Gadag: "Trikuteshwara temple; handloom weaving; Kappatagudda hills",
  Hassan: "Hoysala temples of Belur & Halebidu; potato",
  Haveri: "Byadgi chilli & cardamom trade; Bankapura peacock sanctuary",
  Kalaburagi: "Tur-dal (red gram) bowl; Bahmani fort; limestone",
  Kodagu: "Coffee & Coorg oranges; source of the Kaveri; 'Scotland of India'",
  Kolar: "Kolar Gold Fields (KGF); silk; tomatoes",
  Koppal: "Anegundi (ancient Hampi precinct); granite quarries",
  Mandya: "Sugarcane bowl; KRS dam & Brindavan Gardens on the Kaveri",
  Mysuru: "Dasara & the Mysore Palace; Mysore silk & sandalwood",
  Raichur: "Krishna–Tungabhadra doab paddy; Hutti gold mines",
  Ramanagara: "Asia's biggest silk-cocoon market; 'Sholay' rocks",
  Shivamogga: "Jog Falls; areca nut; 'Gateway to the Malnad'",
  Tumakuru: "Coconut belt; Siddaganga Mutt & Devarayanadurga",
  Udupi: "Krishna Matha & Udupi cuisine; beaches; banking",
  "Uttara Kannada": "Western Ghats forests; Gokarna & Karwar beaches; Kali river",
  Vijayapura: "Gol Gumbaz (whispering dome); Adil Shahi monuments; grapes",
  Yadgir: "Cotton & pulses; the Krishna river; rocky terrain",
};
